server:
  port: 18049

spring:
  profiles:
    active: dev
  #系统名称
  application:
    name: yingluo-common
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: nacos:8848
  config:
    import:
      - optional:nacos:yingluo-common-connection.yml
      - optional:nacos:yingluo-common.yml
  main:
    allow-circular-references: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    clean-disabled: true
    locations:
      - classpath:db/migration/mysql
## dubbo服务注册和发现
dubbo:
  protocol:
    name: dubbo
    port: -1
    id: dubbo
  registry:
    address: zookeeper://zookeeper:2181
  scan:
    base-packages: com.yingluo.common.service.dubbo
  application:
    enable-file-cache: false
    qos-port: 0
#  cloud:
#    subscribed-services: ""


seata:
  enabled: false
  #1.4.2使用此配置禁用seata
  enable-auto-data-source-proxy: false
  application-id: yingluo-common
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: nacos:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: nacos:8848
      group: SEATA_GROUP
      namespace:
      username: "nacos"
      password: "nacos"
