version: "3"

services:
  goodsmongo:
    build: .
    container_name: goodsmongo
    volumes:
      - /logs/goods-order/:/logs/yingluo
    networks:
      - somenetwork


networks:
  somenetwork:
    driver: bridge
